# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudip" do
  name "cloudip"
  desc "CLI tool that identifies which cloud provider owns a given IP address"
  homepage "https://github.com/jongwoo328/cloudip"
  version "0.7.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudip"

  on_macos do
    on_intel do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/cloudip_#{version}_darwin_amd64.tar.gz"
      sha256 "208023fca6cb1283c3b4462704e33ea7b437cef2d59620d3ffdba9a5f2f631c6"
    end
    on_arm do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/cloudip_#{version}_darwin_arm64.tar.gz"
      sha256 "2be1700f593304efcac001971f927c9f223bc1e62b16dd8a0754ca39eff882f0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/cloudip_#{version}_linux_amd64.tar.gz"
      sha256 "a4c10173b38cc18435a27225acf0be7998f6b50ff8e62057b312ea94e5834ab4"
    end
    on_arm do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/cloudip_#{version}_linux_arm64.tar.gz"
      sha256 "edc133229165696c9cc80e581761270078ced8aecb8f286c5892f3e1b03c4c1c"
    end
  end

  # No zap stanza required
end
