# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudip" do
  name "cloudip"
  desc "CLI tool that identifies which cloud provider owns a given IP address"
  homepage "https://github.com/jongwoo328/cloudip"
  version "0.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudip"

  on_macos do
    on_intel do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/archives/cloudip_#{version}_darwin_amd64.tar.gz"
      sha256 "3fdfc35627c0ace429dc9e060743b22d8dab3d02aa7d17917ab4579023d522d9"
    end
    on_arm do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/archives/cloudip_#{version}_darwin_arm64.tar.gz"
      sha256 "235659d1a455fb443bf95d8e22fd2b44e39ee9524a9a37c850f4094c079fa5ea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/archives/cloudip_#{version}_linux_amd64.tar.gz"
      sha256 "c9716a59f87913dff118ad26f3c8b43027de03eeaae3afa98fc18dc9ee6afd7e"
    end
    on_arm do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/archives/cloudip_#{version}_linux_arm64.tar.gz"
      sha256 "cfe590d9152c603d0f39bd576f1dc53d81d7baa38e030fa4e4157e46e5f40239"
    end
  end

  # No zap stanza required
end
