# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudip" do
  version "0.8.1"

  on_macos do
    on_intel do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/cloudip_#{version}_darwin_amd64.tar.gz"
      sha256 "a50d305e84bf1804fe4207b81a53e4c395b5e434bfe5831a204509ed3621118d"
    end
    on_arm do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/cloudip_#{version}_darwin_arm64.tar.gz"
      sha256 "fc466de5e62be5581b51f6f711401f18e045397b0f69a26e4caaa66432ce1b10"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/cloudip_#{version}_linux_amd64.tar.gz"
      sha256 "37806a3ba4760055d35ebd62aeeeada16c194b40276d4c5e6c02a178e780cbcc"
    end
    on_arm do
      url "https://github.com/jongwoo328/cloudip/releases/download/v#{version}/cloudip_#{version}_linux_arm64.tar.gz"
      sha256 "f734292ed5adfba5ef8089c659455e69df566db9a0081d43abf4603322f4ad70"
    end
  end

  name "cloudip"
  desc "CLI tool that identifies which cloud provider owns a given IP address"
  homepage "https://github.com/jongwoo328/cloudip"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudip"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cloudip"]
  end

  # No zap stanza required

end
